title: Architecting the future
description: When inspiration strikes, it lands here. Eventually.
baseurl: ""
url: "https://silkeplessers.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
future: true

kramdown:
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  hard_wrap: false
  parse_block_html: true

# Prevent image compression
image_compression:
  quality: 100
